# Generated by Django 4.1.5 on 2023-01-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='create',
            new_name='created',
        ),
    ]
