# Generated by Django 4.1.5 on 2023-01-23 18:13

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(db_column='phone', default='+11 (067) 111-11-11', max_length=16, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, validators=[students.validators.ValidateEmailDomain, students.validators.validate_unique_email]),
        ),
    ]
