# Generated by Django 4.1.5 on 2023-01-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_phone_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(db_column='phone', default='+11 (067) 111-11-11', max_length=50, verbose_name='Phone'),
        ),
    ]
