# Generated by Django 4.1.5 on 2023-01-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(db_column='phone', max_length=16, verbose_name='Phone'),
        ),
    ]
