# Generated by Django 4.1.5 on 2023-01-29 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='First name', max_length=50)),
                ('last_name', models.CharField(db_column='Last name', max_length=50)),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('salary', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]
