# Generated by Django 4.1.7 on 2023-02-26 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_column='Name', max_length=80, verbose_name='Name')),
                ('start_data', models.DateField(default='2023-06-24')),
                ('description', models.TextField(blank=True, null=True)),
                ('groups_link', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_link', to='groups.group')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
