# Generated by Django 4.1.7 on 2023-02-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_column='name', max_length=80, verbose_name='name')),
                ('start_data', models.DateField(default='2023-06-24')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
