# Generated by Django 4.1.7 on 2023-02-24 21:29

from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('group_name', models.CharField(db_column='G_name', max_length=80, verbose_name='Group name')),
                ('group_start_data', models.DateField(default='2023-06-24', validators=[groups.validators.validate_start_date])),
                ('group_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
