# Generated by Django 4.1.5 on 2023-01-20 09:54

from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='start_data_group',
        ),
        migrations.AddField(
            model_name='group',
            name='group_start_data',
            field=models.DateField(default='2023-06-24', validators=[groups.validators.validate_start_date]),
        ),
    ]
