# Generated by Django 4.1.7 on 2023-02-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('groups', '0003_group_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='headman',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headman_group', to='students.student'),
        ),
    ]
