# Generated by Django 4.1.7 on 2023-03-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='groups',
        ),
    ]
