# Generated by Django 4.1.7 on 2023-02-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='course',
        ),
    ]
